DROP TABLE IF EXISTS users CASCADE;

CREATE TABLE users(
  id SERIAL PRIMARY KEY,
  name VARCHAR(45) NOT NULL UNIQUE,
  password VARCHAR(60) NOT NULL,
  enabled BOOLEAN NOT NULL,
  role VARCHAR(45) NOT NULL
);