DROP TABLE IF EXISTS users CASCADE;

CREATE TABLE users(
  id SERIAL PRIMARY KEY,
  name VARCHAR(64) NOT NULL UNIQUE,
  password VARCHAR(64) NOT NULL,
  enabled BOOLEAN NOT NULL,
  role VARCHAR(64) NOT NULL
);